name: CI

on:
  # push:
  #   branches: [ "main" ]
  #   paths:
  #     - app/**
  # pull_request:
  #   branches: [ "main" ]
  #   paths:
  #     - app/**
  workflow_dispatch:

env:
  REGISTRY: devghactionacr001.azurecr.io
  IMAGE_NAME: demo-fastapi-webapp
  STORAGE_NAME: devghactionsac001
  STORAGE_CONTAINER_NAME: test
  DOWNLOAD_FILENAME: test.txt

jobs:

  continuous-integration-on-cpu:
    runs-on: [self-hosted, general-cpu]
    steps:
    # 1. Checkout Repo
    - uses: actions/checkout@v4

    # 2. Setup Python
    - name: Setup Python
      uses: actions/setup-python@v5.2.0
      with:
        python-version: '3.11.7'
        cache: 'pip' # caching pip dependencies
    
    # 3. Install Requirements and Test Application
    - name: Install Requirements and Test Application
      run: |
          pip install -r requirements.txt
          pytest app/test_rest.py | tee app/test-results-${{ github.sha }}.txt
    
    # 4. Upload Test Result to Blob
    - name: Upload Test Result to Blob - Azure login
      uses: azure/login@v2
      with:
        auth-type: IDENTITY # VM System Assigned Identity
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
    - name: Upload Test Result to Blob - Azure CLI script
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          az storage blob upload \
            --account-name ${{ env.STORAGE_NAME }}  \
            --container-name ${{ env.STORAGE_CONTAINER_NAME }} \
            --name test-results-${{ github.sha }}.txt \
            --file app/test-results-${{ github.sha }}.txt \
            --auth-mode login \
            --overwrite

    # 4. Upload Test Reulst as Artifact to GithubActions
    - name: Upload pytest test results - to GithubActions
      uses: actions/upload-artifact@v4
      with:
        name: pytest-result
        path: app/test-results.txt
      # Use always() to always run this step to publish test results when there are test failures
      if: ${{ always() }}

    # 5. Docker build and push (push to ACR) - Setup Docker
    - name: Docker build and push (push to ACR) - Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    # 5. Docker build and push (push to ACR) - Login to ACR
    - name: Docker build and push (push to ACR) - Docker Login to ACR
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.AZURE_CLIENT_ID }}
        password: ${{ secrets.AZURE_CLIENT_SECRET }}
    
    # 5. Docker build and push (push to ACR)
    - name: Docker build and push (push to ACR) - Build and Push Docker image to ACR
      uses: docker/build-push-action@v6.9.0
      with:
        context: .
        cache-from: type=local,src=/tmp/buildx_cache_dir/
        cache-to: type=local,src=/tmp/buildx_cache_dir/,mode=max
        platforms: linux/amd64
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
    
    # 6. Download Test Tool From Blob
    - name: Download Test Tool From Blob - Azure CLI script
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          az storage blob download \
            --account-name ${{ env.STORAGE_NAME }}  \
            --container-name ${{ env.STORAGE_CONTAINER_NAME }} \
            --name ${{ env.DOWNLOAD_FILENAME }} \
            --file "./${{ env.DOWNLOAD_FILENAME }}"  \
            --auth-mode login

    # 7. Docker run with volume (with download file) (image from ACR)
    - name: Docker run with volume (with download file) (image from ACR)
      run: | 
        docker run -d -p 8080:8080 \
          --name ${{ github.sha }} \
          -v "$(pwd)/${{ env.DOWNLOAD_FILENAME }}":/home/python/${{ env.DOWNLOAD_FILENAME }} \
          -e FILEPATH="/home/python/${{ env.DOWNLOAD_FILENAME }}" \
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
    
    # 8. Test Application
    - name: Docker run with volume (with download file) (image from ACR)
      run: | 
        sleep 5s
        max=10;for (( i=1; i <= $max; ++i ));do curl -I localhost:8080/text >> test4.txt; done
    # 9. Approve or Deny / Notify

    # 10. Stop and Remove Container



    